name: Blocks
form: $/humlnetcreative/pages/models/block/fields.yaml
modelClass: HumlnetCreative\Pages\Models\Block
defaultRedirect: humlnetcreative/pages/blocks
create:
    title: 'humlnetcreative.pages::lang.block.create.title'
    redirect: 'humlnetcreative/pages/blocks/update/:id'
    redirectClose: humlnetcreative/pages/blocks
update:
    title: 'humlnetcreative.pages::lang.block.update.title'
    redirect: humlnetcreative/pages/blocks
    redirectClose: humlnetcreative/pages/blocks
customMessages:
    flashCreate: 'humlnetcreative.pages::lang.block.create.flash'
    flashUpdate: 'humlnetcreative.pages::lang.block.update.flash'
    flashDelete: 'humlnetcreative.pages::lang.block.delete.flash'
