plugin:
    name: 'humlnetcreative.pages::lang.plugin.name'
    description: 'humlnetcreative.pages::lang.plugin.description'
    author: 'Lukáš Záplata'
    icon: oc-icon-desktop
    homepage: ''
navigation:
    main-menu-item:
        label: 'humlnetcreative.pages::lang.plugin.name'
        url: /
        icon: icon-desktop
        permissions:
            - humlnetcreative.pages.default
        sideMenu:
            side-menu-item2:
                label: 'humlnetcreative.pages::lang.menuitem.submenu.homepage.label'
                url: humlnetcreative/pages/blocks
                icon: icon-home
                permissions:
                    - humlnetcreative.pages.block
            side-menu-item:
                label: 'humlnetcreative.pages::lang.menuitem.submenu.structure.label'
                url: humlnetcreative/pages/pages
                icon: icon-sitemap
                permissions:
                    - humlnetcreative.pages.default
            side-menu-builder:
                label: 'Page Builder'
                url: humlnetcreative/pages/builderpages
                icon: icon-th-large
                permissions:
                    - humlnetcreative.pages.builder
            side-menu-blueprint:
                label: 'Import kostry'
                url: humlnetcreative/pages/blueprints
                icon: icon-upload
                permissions:
                    - humlnetcreative.pages.builder.import
permissions:
    humlnetcreative.pages.default:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.default'
    humlnetcreative.pages.content:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.label'
    humlnetcreative.pages.content.create:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.create.label'
    humlnetcreative.pages.content.update:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.label'
    humlnetcreative.pages.content.delete:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.delete.label'
    humlnetcreative.pages.content.update.type:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.type.label'
    humlnetcreative.pages.content.update.posts_category:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.posts_category.label'
    humlnetcreative.pages.content.update.files_category:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.files_category.label'
    humlnetcreative.pages.content.update.flashmessages_category:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.flashmessages_category.label'
    humlnetcreative.pages.content.update.contacts_category:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.contacts_category.label'
    humlnetcreative.pages.content.update.jobs_category:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.jobs_category.label'
    humlnetcreative.pages.content.update.links_category:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.links_category.label'
    humlnetcreative.pages.content.update.partial:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.partial.label'
    humlnetcreative.pages.content.update.row_cols:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.row_cols.label'
    humlnetcreative.pages.content.update.posts_sort_order:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.posts_sort_order.label'
    humlnetcreative.pages.content.update.gallery:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.gallery.label'
    humlnetcreative.pages.content.update.pricelist:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.pricelist.label'
    humlnetcreative.pages.content.update.opening_hours:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.opening_hours.label'
    humlnetcreative.pages.content.update.slider:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.update.slider.label'
    humlnetcreative.pages.content.reorder:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.content.reorder.label'
    humlnetcreative.pages.page:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.page.label'
    humlnetcreative.pages.page.create:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.page.create.label'
    humlnetcreative.pages.page.update:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.page.update.label'
    humlnetcreative.pages.page.delete:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.page.delete.label'
    humlnetcreative.pages.page.reorder:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.page.reorder.label'
    humlnetcreative.pages.page.slider:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.page.slider.label'
    humlnetcreative.pages.block:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.block.label'
    humlnetcreative.pages.block.create:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.block.create.label'
    humlnetcreative.pages.block.update:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.block.update.label'
    humlnetcreative.pages.block.delete:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.block.delete.label'
    humlnetcreative.pages.block.reorder:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.block.reorder.label'
    humlnetcreative.pages.structure:
        tab: 'humlnetcreative.pages::lang.plugin.name'
        label: 'humlnetcreative.pages::lang.permission.structure.label'
