name: Stránka
modelClass: HumlnetCreative\Pages\Models\BuilderPage
form: $/humlnetcreative/pages/models/builder/fields.yaml
defaultRedirect: humlnetcreative/pages/builderpages
create:
    redirect: humlnetcreative/pages/builderpages/update/:id
    redirectClose: humlnetcreative/pages/builderpages
update:
    redirect: humlnetcreative/pages/builderpages
    redirectClose: humlnetcreative/pages/builderpages
customMessages:
    flashCreate: Stránka byla vytvořena jako koncept.
    flashUpdate: Koncept byl uložen.
    flashDelete: Stránka byla odstraněna.
