contents:
    label: Content
    view:
        list: $/humlnetcreative/pages/models/content/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/humlnetcreative/pages/models/content/fields.yaml
        list: $/humlnetcreative/pages/models/content/columns.yaml
    popupSize: adaptive
    customMessages:
        buttonCreate: 'humlnetcreative.pages::lang.content.create.title'
        titleCreateForm: 'humlnetcreative.pages::lang.content.create.title'
        titleUpdateForm: 'humlnetcreative.pages::lang.content.update.title'
