name: Pages
modelClass: HumlnetCreative\Pages\Models\Page
form: $/humlnetcreative/pages/models/page/fields.yaml
defaultRedirect: humlnetcreative/pages/pages
create:
    title: 'humlnetcreative.pages::lang.page.create.title'
    redirect: 'humlnetcreative/pages/pages/update/:id'
    redirectClose: humlnetcreative/pages/pages
update:
    title: 'humlnetcreative.pages::lang.page.update.title'
    redirect: humlnetcreative/pages/pages
    redirectClose: humlnetcreative/pages/pages
customMessages:
    flashCreate: 'humlnetcreative.pages::lang.page.create.flash'
    flashUpdate: 'humlnetcreative.pages::lang.page.update.flash'
    flashDelete: 'humlnetcreative.pages::lang.page.delete.flash'
